language: python
sudo: false
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - "pip install -e ."
  - "pip install coveralls"
  - "pip install pyflakes"
  - "pip install pycodestyle"
  - "pip install pylint"

script:
  - "coverage run --source=validation setup.py test"
  - "pycodestyle validation setup.py"
  - "pyflakes validation setup.py"
  - "pylint -E validation setup.py"

after_success:
  - "coveralls"
