language: python
sudo: false

jobs:
  include:
    - stage: coveralls
      python: 3.6
      install:
        - "pip install -e ."
        - "pip install coveralls"
      script:
        - "coverage run --source=validation setup.py test"
      after_success:
        - "coveralls"

    - stage: test
      python:
        - "2.7"
        - "3.4"
        - "3.5"
        - "3.6"
      install:
        - "pip install -e ."
      script:
        - "python setup.py test"

    - stage: pylint
      python:
        - "2.7"
        - "3.6"
      install:
        - "pip install -e ."
        - "pip install pylint"
      script:
        - "pylint -E validation setup.py"

    - stage: pycodestyle
      python:
        - "3.6"
      install:
        - "pip install pycodestyle"
      script:
        - "pycodestyle validation setup.py"

    - stage: pyflakes
      python:
        - "3.6"
      install:
        - "pip install pyflakes"
      script:
        - "pyflakes validation setup.py"
